apiVersion: v1
kind: ConfigMap
metadata:
  name: r3mes-config
  namespace: r3mes
data:
  R3MES_ENV: "production"
  LOG_LEVEL: "INFO"
  ENABLE_FILE_LOGGING: "true"
  DATABASE_POOL_MIN_SIZE: "10"
  DATABASE_POOL_MAX_SIZE: "50"
  RATE_LIMIT_CHAT: "10/minute"
  RATE_LIMIT_GET: "30/minute"
  # Add other non-sensitive configuration here

